export default data =
    [
        {
            key: "1",
            title: "Ahinjiro",
            contenu: "Ahinjiro avy any ambony ny tanana \nAfaho aho ka vonjeo \nNy feoko no hitarainako \nSy hifonako Aminao \n\nFaingana hamonjy ahy \nFaingana hanampy \nJehovah ô! Mba mitalaho \nJehovah ô! Valio aho \n\nAfeno eo ambany elatrao aho \nMba hitoetra amim-piadanana \nlanao tokiko \nIanao no andriko ",
            refrain: "",
        },
        {
            key: "2",
            title: "Akore Avao",
            contenu: "Akore avao, holongoko \nIhe he, nbe tondrenge \nTsy tany to, hihomake \nVasiagneo, hirarakeo \n\nJesoa tsy handefitse e! \nHanampoke izay tondregne \nZay mino, horaise e! \nF'izay tsy mino, tsy horaise e!",
            refrain: "Aia aia, ty hombao o! Lemirerere \nAmandranomaso Hifitsefitse (2)",
        },
        {
            key: "3",
            title: "Andro Noely",
            contenu: "Andro noely, mahafinaritra \nNy ankizy kely mihoby fatratra \nAndro noely, ilay fety sambatra \nIreo anjely mihoby fatratra \n\nAndro noely, aoka isika hidera ny Tompo \nAndro noely, noho ny fitiavany \nAndro noely, ireo zava-mahagaga vitany \nAndro noely, ho an'olombelona",
            refrain:"",
        },
        {
            key: "4",
            title: "Avia Fanahy Masina",
            contenu: " Manatreha anay eto Ianao izao, Fanahy ô! \nMitomoera Ianao anatinay izao, Fanahy ô! (2) \n\nFanahy Tsara Ianao, be voninahitra Ianao \nFanahy mahery indrindra, ambony indrindra Masina Ianao (2)",
            refrain:" Avia Fanahy Masina ô! Midina \nAvia Fanahy Masina ô! Midina \nAvia Fanahy Masina ô! Midina \n Avia Fanahy Masina ô! Midina",
        },
        {
            key: "5",
            title: "Baikonao ry Tompo",
            contenu: "Baikonao ry Tompo ô! \nHoe mifankatiava \nSitrakao ry Tompo o \nNy mifankatia (2) \n\nInty aho Tompo ô! \nHo vonona hanaiky Anao \nTanterahinay ny baiko \nNapetrakao (2)",
            refrain:"Halanao ny mifandrafy \nTsy tianao ny toetra ratsy (2)",
        },
        {
            key: "6",
            title: "Faly sy Ravo",
            contenu: "Faly sy ravo ary koa handihy \nNy midera Anao Andriamanitro \nNy foko mifaly, ny saiko mifaly \nFanahiko hihoby, izaho koa handihy",
            refrain:"Tsara ny midera \nTsara ny mihoby \n\nTsy foinay ny fiderana \nSitrakay ny fihobiana \nMaminay ny mankalaza \nHery ho anay ny fiderana",
        },
        {
            key: "7",
            title: "Fandalovana",
            contenu: "Fiderana Anao ny fiainana any \nFitoerana any am-paradisa masina \nFiderana Anao ny fiainana any \nFa ampahany ihany ny anay ety",
            refrain:"Fandalovana ihany ny eto an-tany \nFa ny tena fiainana any ankoatra \nFa ny tena fiainana any ankoatra \nTsisy fetra ny any am-paradisa \n\nTompo ô! Dera ho Anao \nOuh! Ouh! Ouh! Ouh! Ouh! Ouh! Dera ho Anao",
        },
        {
            key: "8",
            title: "Fiaretan' ny Tompo",
            contenu: "Voasatro-tsilo lanao sady notsaraina \nNozakainao izany na dia mangidy aza (2)\nFanamelohana ho faty no sazy nomena Anao \nNefa lanao anie madio tsy manan-tsiny \n\nNitondra ny hazo fijaliana \nFanetren-tena no nomenao (2) \nNa dia lavo aza Ianao \nTsy mba nitaraina na niteny \n\nMaro ny anjely naniry hanampy Anao \nNefa nalehonao olombelona ihany (2) \nNy vehivavy sy ny reninao nitomany Anao \nNefa dia nasetrinao teny feno fitiavana \n\nNesorina ny fitafianao \nNefa tsy noheverinao ny henatr'olona (2) \nNohombohana tamin'ny hazo fijaliana \nMenatra izahay ry Tompo noho ny helokay \n\nMaty ny Mpamponjy voasolo ny helokay \nRehefa niteny teny feno fitiavana (2) \nNampidinina ny tenany \nEfa vita izao ny asa fanavotana \n\nRaisin'ny fasana ny Tompon'ny aina \nSambatra ny maty ao aminao (2) \nMiora zava-manitra entina ahosotra \nMiora zava-manitra entina ahosotra",
            refrain:"Noho ny helokay no nahatonga izany \nHiezaka izahay Anao ny sitraponao, Tompo o! \n\nTia anay lanao ry Tompo ary tena tia anay \nFiaretana lehibe, no nitiavanao anay (2)",
        },
        {
            key: "9",
            title: "Haleloia",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "10",
            title: "Indro fa Tonga ilay Fitiavana",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "11",
            title: "Inty Aho",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
        },
        {
            key: "12",
            title: "Isaorana",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "13",
            title: "Lehibe ny Voninahitrao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "14",
            title: "Mamindra fo Amiko",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "15",
            title: "Mampahery",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "16",
            title: "Mamy ny Midera",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "17",
            title: "Mandehana ry Tanora",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "18",
            title: "Mba Miverena",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "19",
            title: "Miantso Anao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "20",
            title: "Misy Hery",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "21",
            title: "Noho ireo Soa",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "22",
            title: "Nomen' ny Ray",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "23",
            title: "Ny Feonao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "24",
            title: "Ny Foko sy Saiko",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "25",
            title: "Ny Tananao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "26",
            title: "Ny Tsio-drivotra",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "27",
            title: "O ry Tompo o",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "28",
            title: "Salamo 150",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "29",
            title: "Taloha sy Ankehitriny",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "30",
            title: "Tonga ny Mpamonjy",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "31",
            title: "Valin-teny Eny",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "32",
            title: "Vavaka",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },


    ]