export default data =
    [
        {
            key: "1",
            title: "Ahinjiro",
            contenu: "Ahinjiro avy any ambony ny tanana \nAfaho aho ka vonjeo \nNy feoko no hitarainako \nSy hifonako Aminao \n\nFaingana hamonjy ahy \nFaingana hanampy \nJehovah ô! Mba mitalaho \nJehovah ô! Valio aho \n\nAfeno eo ambany elatrao aho \nMba hitoetra amim-piadanana \nlanao tokiko \nIanao no andriko ",
            refrain: "",
        },
        {
            key: "2",
            title: "Akore Avao",
            contenu: "Akore avao, holongoko \nIhe he, nbe tondrenge \nTsy tany to, hihomake \nVasiagneo, hirarakeo \n\nJesoa tsy handefitse e! \nHanampoke izay tondregne \nZay mino, horaise e! \nF'izay tsy mino, tsy horaise e!",
            refrain: "Aia aia, ty hombao o! Lemirerere \nAmandranomaso Hifitsefitse (2)",
        },
        {
            key: "3",
            title: "Andro Noely",
            contenu: "Andro noely, mahafinaritra \nNy ankizy kely mihoby fatratra \nAndro noely, ilay fety sambatra \nIreo anjely mihoby fatratra \n\nAndro noely, aoka isika hidera ny Tompo \nAndro noely, noho ny fitiavany \nAndro noely, ireo zava-mahagaga vitany \nAndro noely, ho an'olombelona",
            refrain:"",
        },
        {
            key: "4",
            title: "Avia Fanahy Masina",
            contenu: " Manatreha anay eto Ianao izao, Fanahy ô! \nMitomoera Ianao anatinay izao, Fanahy ô! (2) \n\nFanahy Tsara Ianao, be voninahitra Ianao \nFanahy mahery indrindra, ambony indrindra Masina Ianao (2)",
            refrain:" Avia Fanahy Masina ô! Midina \nAvia Fanahy Masina ô! Midina \nAvia Fanahy Masina ô! Midina \n Avia Fanahy Masina ô! Midina",
        },
        {
            key: "5",
            title: "Baikonao ry Tompo",
            contenu: "Baikonao ry Tompo ô! \nHoe mifankatiava \nSitrakao ry Tompo o \nNy mifankatia (2) \n\nInty aho Tompo ô! \nHo vonona hanaiky Anao \nTanterahinay ny baiko \nNapetrakao (2)",
            refrain:"Halanao ny mifandrafy \nTsy tianao ny toetra ratsy (2)",
        },
        {
            key: "6",
            title: "Faly sy Ravo",
            contenu: "Faly sy ravo ary koa handihy \nNy midera Anao Andriamanitro \nNy foko mifaly, ny saiko mifaly \nFanahiko hihoby, izaho koa handihy",
            refrain:"Tsara ny midera \nTsara ny mihoby \n\nTsy foinay ny fiderana \nSitrakay ny fihobiana \nMaminay ny mankalaza \nHery ho anay ny fiderana",
        },
        {
            key: "7",
            title: "Fandalovana",
            contenu: "Fiderana Anao ny fiainana any \nFitoerana any am-paradisa masina \nFiderana Anao ny fiainana any \nFa ampahany ihany ny anay ety",
            refrain:"Fandalovana ihany ny eto an-tany \nFa ny tena fiainana any ankoatra \nFa ny tena fiainana any ankoatra \nTsisy fetra ny any am-paradisa \n\nTompo ô! Dera ho Anao \nOuh! Ouh! Ouh! Ouh! Ouh! Ouh! Dera ho Anao",
        },
        {
            key: "8",
            title: "Fiaretan' ny Tompo",
            contenu: "Voasatro-tsilo lanao sady notsaraina \nNozakainao izany na dia mangidy aza (2)\nFanamelohana ho faty no sazy nomena Anao \nNefa lanao anie madio tsy manan-tsiny \n\nNitondra ny hazo fijaliana \nFanetren-tena no nomenao (2) \nNa dia lavo aza Ianao \nTsy mba nitaraina na niteny \n\nMaro ny anjely naniry hanampy Anao \nNefa nalehonao olombelona ihany (2) \nNy vehivavy sy ny reninao nitomany Anao \nNefa dia nasetrinao teny feno fitiavana \n\nNesorina ny fitafianao \nNefa tsy noheverinao ny henatr'olona (2) \nNohombohana tamin'ny hazo fijaliana \nMenatra izahay ry Tompo noho ny helokay \n\nMaty ny Mpamponjy voasolo ny helokay \nRehefa niteny teny feno fitiavana (2) \nNampidinina ny tenany \nEfa vita izao ny asa fanavotana \n\nRaisin'ny fasana ny Tompon'ny aina \nSambatra ny maty ao aminao (2) \nMiora zava-manitra entina ahosotra \nMiora zava-manitra entina ahosotra",
            refrain:"Noho ny helokay no nahatonga izany \nHiezaka izahay Anao ny sitraponao, Tompo o! \n\nTia anay lanao ry Tompo ary tena tia anay \nFiaretana lehibe, no nitiavanao anay (2)",
        },
        {
            key: "9",
            title: "Haleloia",
            contenu: "Famonjena lehibe \nFiadanana ho antsika \nHafaliana tsisy fetra \n\nNo nomen'ny Tompo \nKa hirao ny HALELOIA (2)",
            refrain:"Haleloia haleloia derao ny Tompo \nHaleloia haleloia hobio ny Tompo (2)",
        },
        {
            key: "10",
            title: "Indro fa Tonga ilay Fitiavana",
            contenu: "Indro fa tonga ilay fitiavana \nMonina eto indray hitondra hazavana \nFahasoavana lehibe tokoa \nAnkehintriny no tafatoetra \nKa andeha iaraka isika hanome \nVoninahitra sy ny haja ary ny dera",
            refrain:"An'ilay Jesoa, Jesoa, Jesoa, Jesoa Kristy Tompontsika (2)",
        },
        {
            key: "11",
            title: "Inty Aho",
            contenu: "Inty aho Tompo o! \nMiantso ny anaranao \nMba henoy ny feoko \nMitaraina Aminao \nFa maro ireo fankam-panahy \nIzay mambabo ahy \nO vonjeo Tompo ô! (2 x) (2) \n\nTsapako ankehitriny \nNy fitiavanao ahy \nF’lanao ilay tsy manan-tsiny \nNo indro tonga hamonjy ahy \nKa raha ho avy ilay fotoana \nHiverenanao ety \nRaiso aho Tompo ô! (2 x) (2)",
            refrain:"Ianao no fiainako \nSy mba itokiako \nTsy misy hatahorako \nN'inonan'inona manjo \nRavoravo izany foko \nRaha horaisinao tokoa \nAnjakao ny fiainako (2 x)",
        },
        {
            key: "12",
            title: "Isaorana",
            contenu: "Isaorana lanao \nIzay mitantana ny dianay \nIzay misava ny làlanay (2fois) (2) \n\nArovanao ny finoanay \nMba tsy ho faty \nArovanao ny finoanay \nKa ho velona",
            refrain:"Amboarinao ny lalanay mba tsy ho potraka (2 fois) \nFa maro ireo olana sedrainay (2 fois)",
        },
        {
            key: "13",
            title: "Lehibe ny Voninahitrao",
            contenu: "Lehibe ny voninahitrao \nTsy misy toa Anao \nManerana izao tontolo izao \nNy asanao (2 \n\n   Asa tananao izahay \n   Ary nokalihanao \n   Notendrenao izahay \n   Fa sarobidy taminao \n\nTsisy mahalaza ny halebehano \nIzao rehetra izao \nTsisy mahafehy ny herinao \nIzao tontolo izao \n\n   Gaga sy talanjona \n   Izao rehetra izao \n   Ka mihankohoka \n   Sy manaiky Anao)",
            refrain:"Ka dera sy laza ho Anao",
        },
        {
            key: "14",
            title: "Mamindra fo Amiko",
            contenu: "Mamindra fo amiko, Andriamanitra ô ! \nMihaino ny fivavako \nHenoy aho ka valio \nMangorohoro ny fanahiko \nMamely ahy ny tahotra \nMitomany ny foko \nMiandry Anao aho Tompo! \n\nAza esorina aminay \nAoka hitoetra ao anatinay \nNy fahasoavanao \nMomba anay ry Tompo ô! \nN'aiza n'aiza misy anay \nFa Tompo tsara ianao \nAry Andriamanitray",
            refrain:"Henoy ny feoko \nRaha mitaraina aho \nF'ianao irery no tokiko \nMandrakizay (2)",
        },
        {
            key: "15",
            title: "Mampahery",
            contenu: "Mampahery ny saiko marefo \nIreo teny izay voalazanao \nIndrindra moa raha misy mahory \nFiononako ilay teninao \n\nNy fahazavanao no hitarafako \nIzay rehetra halehako \nTsy mba misy zava-bitako \nRaha tsy eo lanao \nEfa fantatro \nHatrizay \nFa momba ahy lanao \n\nNy maraim-baovao \nDia avy aminao \nNa koa ny alina mikitroka isaoranay Anao \nNoho izany indrindra hatramin'izao \nMankalaza izahay",
            refrain:"",
        },
        {
            key: "16",
            title: "Mamy ny Midera",
            contenu: "Misy zavatra iray \nMahalasa saina anay \nFa rehefa midera Anao \nDia mahazo hery vaovao (2) \n\nMaro ireo fitsapana \nEo koa ny fisedrana \nFa maivana izany \nNoho ilay fiderana (2)",
            refrain:"Tsy hitandroanay hasasarana \nNy fanaovana izany \nFa amin'ny fo, fanahy, saina iray \nSatria mamy ny midera Anao (2)",
        },
        {
            key: "17",
            title: "Mandehana ry Tanora",
            contenu: "Mba mandehana ry tanora \nMiderà isan'andro, isan' ora \nMirosoa hatrany hatrany \nMivavaha raha mbola eto an-tany(2) \n\nFantaro ny zava-drehetra \nAtaovy avokoa tsy misy fepetra \nMahaiza mamindra mba tsy ho solafaka \nTompo tsy hanary anao any an-davaka(2)",
            refrain:"Ny hatanorana misy ny Tompo \nTsisy tomnany tsisy toloko \nTontosa avokoa izay kasaina \nNy Tompo Jesoa manolon-tsaina (2)",
        },
        {
            key: "18",
            title: "Mba Miverena",
            contenu: "Mba miverena, ry mpanota ô! \nFa Izaho no làlana \nSy fahamarinana ary fiainana \nAmpy ho anao ny fiadanana (2)",
            refrain:"Tsy sitrako anefa \nNy hitoeranao \nAo anaty ota sy faharatsiana \nFa mbola miantso aho \nKa miverena \nFandrao diso \nAorina loatra",
        },
        {
            key: "19",
            title: "Miantso Anao",
            contenu: "Ry Jehovah Tompo ô! \nIndro aho mitady Anao \nAza avela irery aho \nFa ataovy eo anilanao \n\nFaingana ry Tompo ô! \nAiza lanao? \nMidina ato anatiko \nFa rànao no ilaiko",
            refrain:"Aza hariana aho re! \nNa dia mpanota aza \nOmbao ny fanahinao \nNa dia tsy mendrika aza \nAza hariana aho re! \nNa dia mpanota aza \nRy Jehovah Tompo ô!",
        },
        {
            key: "20",
            title: "Misy Hery",
            contenu: "Misy hery, Hery lehibe \nManasitrana ireo marary \nMisy hery, Hery lehibe \nManafaka ny gadra (2) \n\nTsy ho kivy intsony aho \nFa misy hery ao anatiko \nTsy hahatahotra anie aho \nF'efa itoerany (2) \n\nHisaorako i Kristy \nVelona ato am-poko \naly aho (2 fois) fa naharay azy \nHALELOIA (2)",
            refrain:"Aoka isika hidera an'Azy \nAoka isika hihoby an'Azy \nAoka isika hankalaza an'Azy \nAoka isika hisaotra an'Azy (2)",
        },
        {
            key: "21",
            title: "Noho ireo Soa",
            contenu: "Noho ireo soa marobe \nIzay nataonao anay tety \nMisaotra Anao, mitsaoka Anao \nSitraka ho Anao, Andriamanitra ô! (2) \n\nAmin'ny fonay sy ny sainay \nAry ny fanahy no isaoranay Anao \n\nNOVAHANAO NY FATOTRAY \nNOTANTANANAO NY LALANAY \nFAMINDRAM-PO MANDRAKIZAY \nIZANY REHETRA IZANY \nNO ISAORANAY (2)",
            refrain:"",
        },
        {
            key: "22",
            title: "Nomen' ny Ray",
            contenu: "Nomen'ny Ray ny zanany \nNafoiny ho antsika ho famonjena \nNatolony ny rehetra ho avotra \nNampiaretany ny mafy \n\nNanaiky ny Rainy ny zanany \nNahafoy ny voninahitra any an-danitra \nNanaiky ny Rainy ny zanany \nNiaritra fahafatesana ho avy \n\nMendrika ho ankalazaina ny anarany \nMendrika ho deraina ny famonjeny \nMendrika ny hihobiana ny fandreseny \nMendrika ankasitrahana ny fitiavany \n\nNandresy ny zanany \nVoasokatra ho antsika ny lanitra \nMiandry ny fiaviany isika \nFiadanana tsisy fetra no setriny \n\nKa Ka aoka ho hambarantsika",
            refrain:"",
        },
        {
            key: "23",
            title: "Ny Feonao",
            contenu: "",
            refrain:"",
        },
        {
            key: "24",
            title: "Ny Foko sy Saiko",
            contenu: "",
            refrain:"",
        },
        {
            key: "25",
            title: "Ny Tananao",
            contenu: "",
            refrain:"",
        },
        {
            key: "26",
            title: "Ny Tsio-drivotra",
            contenu: "",
            refrain:"",
        },
        {
            key: "27",
            title: "O ry Tompo o",
            contenu: "",
            refrain:"",
        },
        {
            key: "28",
            title: "Salamo 150",
            contenu: "",
            refrain:"",
        },
        {
            key: "29",
            title: "Taloha sy Ankehitriny",
            contenu: "",
            refrain:"",
        },
        {
            key: "30",
            title: "Tonga ny Mpamonjy",
            contenu: "",
            refrain:"",
        },
        {
            key: "31",
            title: "Valin-teny Eny",
            contenu: "",
            refrain:"",
        },
        {
            key: "32",
            title: "Vavaka",
            contenu: "",
            refrain:"",
        },


    ]