export default data =
    [
        {
            key: "1",
            title: "Ahinjiro",
            contenu: " Ahinjiro avy any ambony ny tanana \n Afaho aho ka vonjeo \n Ny feoko no hitarainako \n Sy hifonako Aminao \n \n Faingana hamonjy ahy \n Faingana hanampy \n Jehovah ô! Mba mitalaho \n Jehovah ô! Valio aho \n\n Afeno eo ambany elatrao aho \n Mba hitoetra amim-piadanana \n lanao tokiko \n lanao no andriko ",
            refrain: "",
        },
        {
            key: "2",
            title: "Akore Avao",
            contenu: " Akore avao, holongoko \n Ihe he, nbe tondrenge \n Tsy tany to, hihomake \n Vasiagneo, hirarakeo \n\n Jesoa tsy handefitse e! \n Hanampoke izay tondregne \n Zay mino, horaise e! \n F'izay tsy mino, tsy horaise e!",
            refrain: " Aia aia, ty hombao o! Lemirerere \n Amandranomaso Hifitsefitse (2)",
        },
        {
            key: "3",
            title: "Andro Noely",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "4",
            title: "Avia Fanahy Masina",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "5",
            title: "Baikonao ry Tompo",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "6",
            title: "Faly sy Ravo",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "7",
            title: "Fandalovana",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "8",
            title: "Fiaretan' ny Tompo",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "9",
            title: "Haleloia",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "10",
            title: "Indro fa Tonga ilay Fitiavana",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "11",
            title: "Inty Aho",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
        },
        {
            key: "12",
            title: "Isaorana",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "13",
            title: "Lehibe ny Voninahitrao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "14",
            title: "Mamindra fo Amiko",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "15",
            title: "Mampahery",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "16",
            title: "Mamy ny Midera",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "17",
            title: "Mandehana ry Tanora",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "18",
            title: "Mba Miverena",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "19",
            title: "Miantso Anao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "20",
            title: "Misy Hery",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "21",
            title: "Noho ireo Soa",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "22",
            title: "Nomen' ny Ray",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "23",
            title: "Ny Feonao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "24",
            title: "Ny Foko sy Saiko",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "25",
            title: "Ny Tananao",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "26",
            title: "Ny Tsio-drivotra",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "27",
            title: "O ry Tompo o",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "28",
            title: "Salamo 150",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "29",
            title: "Taloha sy Ankehitriny",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "30",
            title: "Tonga ny Mpamonjy",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "31",
            title: "Valin-teny Eny",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },
        {
            key: "32",
            title: "Vavaka",
            contenu: "Ahinjiro avy any ambony ny tanana Afaho aho ka vonjeo Ny feoko no hitarainako  Sy hifonako Aminao",
            refrain:"",
        },


    ]